- app/templates/donations.html
Without the http/https the usb.org link was having https://fwupd.org prepended to it creating an invalid link.
> Fixed invalid link

- README.md
- app/flaskapp.cfg
- app/foreign_archive.py
- app/views.py
- cabarchive/archive.py
Microsoft requires .CAB file to upload to Windows Hardware Dev Center, however
after the content is signed by Microsoft, it's unavailable in .CAB format from
Hardware Dev Center. It's instead distributed using .ZIP file.
Allow LVFS to accept the ZIP file format and repack it into CAB. This will make
it easier to re-use content otherwise headed to Windows Update.
Fixes https://github.com/hughsie/lvfs-website/issues/20
> Support uploading MSZIP files

- app/uploadedfile.py
- uploadedfile_test.py
This prevents vendors doing things like 'Please refer to README.txt'.
Fixes https://github.com/hughsie/lvfs-website/issues/78
> Do not allow release notes to reference missing files

- app/models.py
- app/templates/device.html
- app/templates/firmware-details.html
- app/templates/metainfo.html
- app/uploadedfile.py
- app/views_upload.py
- contrib/Dockerfile
- uploadedfile_test.py
For arguable reasons, some vendors want to hide the direct download links for
firmware on the LVFS pages. This means the firmware files are only available to
download by programs that parse the XML metadata, for instance gnome-software
and fwupdmgr.
To migrate, do:
ALTER TABLE firmware ADD inhibit_download TINYINT DEFAULT 0;
To use this in firmware files, include a section in the metainfo.xml as follows:
<custom>
<value key=LVFS::InhibitDownload/>
</custom>
> Allow vendors to hide the direct download link in the search results

- app/__init__.py
- app/models.py
- app/templates/agreement-admin.html
- app/templates/agreement-list.html
- app/templates/agreement.html
- app/templates/default.html
- app/templates/upload.html
- app/views_agreement.py
- app/views_upload.py
- lvfs_test.py
- migrations/versions/06b354728f66_add_the_legal_agreements.py
Also, add the ability to version the agreements and only prompt users of the
LVFS to re-accept the terms when the version number changes.
We need this for the migration to the Linux Foundation, where users will have
to agree that a different legal entity is going to be distributing thier
firmware. The LF legal team also want to polish up the current agreement.
> Only show the legal agreement once rather than on every upload

- app/metadata.py
Using Windows Update the CHIDs are treated as 'OR' when matching and we should
probably follow the same logic to avoid confusing people.
Requires the fwupd daemon fix obviously too before it will work on real
hardware with the new-style requirements metadata from the LVFS.
Fixes https://github.com/hughsie/lvfs-website/issues/110
> Only generate one HWID requirement if multiple are used

- app/templates/firmware-problems.html
- app/views.py
- app/views_firmware.py
- lvfs_test.py
Provide the user with the information they need, but don't allow them to log in
with the old username.
In September we'll be be removing the old usernames completely as the GDPR
and product security make it important to map accounts to specific people.
> Deprecate old usernames harder

- app/views_metadata.py
This allows users and QA testers to upload reports to the LVFS when the firmware
archive is downloaded from an embargoed remote.
> Set a ReportURI in the embargo remote

- app/metadata.py
- app/models.py
- app/templates/firmware-components.html
- app/templates/firmware-md-overview.html
- app/views_upload.py
- migrations/versions/3fd6598319ec_add_component_priority.py
This allows us to set the priority of a specific component to be largest, which
allows fwupd to order the results with the 'main' entity listed first.
The other way to do this is to simply add the files into the source .cab file
in a specific order, but I think that's fragile. It's better to be explicit
rather than relying on an assumption that the file order won't be changed when
the archive is repacked.
> Allow components to have a priority

- app/templates/docs-users.html
It confused one ODM how fwupd was able to get around the SecureBoot signing
requirements.
> Clarify a statement about signing

- app/metadata.py
- contrib/Dockerfile
Using appstream-glib was convenient, but behind the scenes it was merging
elements like releases in each components in ways that we didn't want.
It's also using a slegdehammer to crack a nut; so lets make things simpler.
Fixes: https://github.com/hughsie/fwupd/issues/818
> Use lxml to produce the XML remote metadata

- app/metadata.py
- app/models.py
- app/templates/firmware-details.html
- app/views_firmware.py
- app/views_upload.py
- migrations/versions/688568bacd0a_add_firmware_is_dirty.py
At the moment moving a firmware from testing to stable shows a message
'The stable metadata will be signed in 16 minutes'
This tells the vendor that the firmware will be soon included in the metadata.
This *also* shows on any firmware currently in stable, which means vendors are
not sure if older firmwares are actually included at that moment. Now there are
lots of different vendors using the LVFS every day, it means it's frequently
unclear what firmware is actually in the metadata at the present time.
To fix this, include a per-firmware flag that is supposed to represent 'is this
firmware pending for the requested metadata for the selected target'.
When the firmware changes remote it is 'dirtied' and once the metadata has been
successfully regenerated and signed it is marked as clean. …
> Add a per-firmware is_dirty boolean flag

- app/templates/vendor-users.html
- app/views_vendor.py
On the LVFS we usually put the 'action widget' as a button on the right hand
side of a table. In the per-vendor users view the common action was actually
going to the details, which meant you had to know you could click on the email
address. The uncommon action was a big red scary 'Disable' button that made it
look even more like this was the only way to interact with the table row.
Use a less scary 'Details' button like the rest of the LVFS, and remove the
one-click-disable misfeature.
> Make the action more obvious when managing vendor users

- app/templates/metadata.html
- app/views_metadata.py
If we're debugging an issue invalidating all the remotes is too large a hammer.
> Allow marking just one remote as dirty

- app/dbutils.py
- app/metadata.py
- app/models.py
- app/static/style.css
- app/templates/firmware-limits.html
- app/templates/firmware-md-overview.html
- app/templates/firmware-md-requires.html
- app/views_component.py
- app/views_upload.py
- migrations/versions/031e02cbc569_add_device_checksum.py
Some firmware has a different on-device checksum to the hash of the firmware
file itself. This may be because:
* The content is not a binary file, e.g. Intel HEX or SREC
* Only part of the firmware is flashed, e.g. ignoring the bootloader section
* The device checksum is calculated using another method entirely, e.g. PCR0
> Allow specifying a device checksum in the metainfo.xml file

- app/templates/device.html
This change adds currently displayed device name to the page title. Having device name there makes it easy to look for a previously visited device in browser history. This may also have a positive impact on search engine positioning.
I was considering an alternative where the most specific string is on the left (e.g. "XPS 13 9350 System Update - Device - LVFS") for when a page title is displayed in a shrunk page tab.
To be honest I didn't test this change but I reused the placeholder from device name so I hope it works :)
Thank you for taking the time to review this PR!
> Add device name to page title

- app/models.py
- app/templates/user-event.html
- app/templates/user-nav.html
- app/templates/vendor-event.html
- app/templates/vendor-nav.html
- app/views_vendor.py
With all the activity on the LVFS, it's not hugely useful to have one global
event log anymore.
Also, setting up a cascade relation between the event_log and the users table
means we can delete users without manually touching the database beforehand.
> Show per-user and per-vendor event logs

- app/models.py
- app/templates/component-nav.html
- app/templates/component-requires-advanced.html
- app/templates/component-requires.html
- app/views_component.py
- lvfs_test.py
For the uncommon case of a firmware with a GUID requirement, or where a version
range is required switch to an 'advanced' table view that allows the user to
both view all existing requirements and to add more.
Fixes https://github.com/hughsie/lvfs-website/issues/221
> Show a detailed component requirement view when required

- app/models.py
- app/pluginloader.py
- app/templates/component-assays.html
- app/templates/component-nav.html
- app/templates/firmware-problems.html
- app/util.py
- app/views_component.py
- app/views_upload.py
- cron.py
- migrations/versions/c3d10b2a239c_add_assays.py
- plugins/uefi-capsule/__init__.py
Initially, add a simple plugin that checks the UEFI capsule header. Later we
could add further firmware analysis like uefi-firmware-parser or perhaps even
something like CHIPSEC.
Running this as a cron job every 5 minutes means the main uWSGI thread is not
waiting for the result, which means we could even do a malware scan which takes
a minute or two to complete.
Failures in the assay means a problem is added to the firmware, which prevents
it being moved to testing and stable. Some failures are waivable by a QA user
which means a problem is no longer generated.
> Perform 'offline' runtime checks on uploaded firmware

- app/static/img/cross.svg
- app/static/img/tick.svg
Closes #270.
Apparently, the `clip-path` inside the embedded styles are considered harmful in Firefox's CSRF protection. Since the icons are really simple, those embedded styles are not really needed either.
This simplification should make them display correctly. (I couldn't test that because CSRF protection is disabled for `http://localhost` / `file://`.)
> Simplify cross/tick icons to make them display in Firefox

- plugins/uefi-capsule/__init__.py
Only the capsule header has to be aligned to the 4kB page size.
Fixes: https://github.com/hughsie/lvfs-website/issues/236
> Don't enforce a 4kB capsule header size

- app/views_report.py
In https://github.com/hughsie/fwupd/commit/06ef7f7e46b79e840e176f913f54b58fbc948c6a
I stated the LVFS doesn't use the ChecksumDevice data. It turns out we do,
but only to count...
In case we start using the checksum in a cleverer way in the future don't store
the Python list.__str__ output in the db, converting all lists the same way.
> Store the device checksums in the database correctly

- app/templates/default.html
- app/templates/firmware-new.html
- app/views_firmware.py
I'm often asked this, and from a personal point of view it's easier in a list
than sorting through the event log and checking which firmware is in testing or
stable.
> Add a page showing new firmware on the LVFS

- app/models.py
- app/templates/docs-vendors.html
- app/templates/firmware-details.html
- app/templates/vendor-details.html
- app/views.py
- app/views_upload.py
- app/views_vendor.py
- contrib/Dockerfile
- migrations/versions/b298782e35cb_add_banned_country_codes.py
- requirements.txt
This is using the free GeoIP data and is optional, and best-effort.
To test, you need to do: yum install geolite2-country python-GeoIP
> Allow vendors to disallow firmware downloads from specific countries

- app/uploadedfile.py
The arguably more correct fix would be to update GLib to a newer version, but
that's somewhat hard for the version of RHEL-7 in production.
Just check the data before we call into GObjectIntrospection.
> Do not crash when parsing invalid metainfo files with invalid UTF-8

- app/util.py
This should only break the line into two parts, so 1 should be used as the number of splits. Set to 2, the code raises ValueError when parsing "Signature status: verification failed: Public key signature verification has failed.". Without this change I think it would be slightly easier to pull off something like CVE-2018-12020 as an attacker.
I haven't tested running the app with this change. I really just wanted to comment - feel free to deny this PR.
> correct the number of splits when parsing certtool

- app/__init__.py
- app/metadata.py
- app/models.py
- app/templates/category-details.html
- app/templates/category-list.html
- app/templates/component-overview.html
- app/templates/devicelist.html
- app/templates/docs-metainfo-category.html
- app/templates/firmware-new.html
- app/templates/firmware-problems.html
- app/templates/private.html
- app/templates/public.html
- app/util.py
- app/views.py
- app/views_category.py
- app/views_component.py
- app/views_upload.py
- lvfs_test.py
- migrations/versions/b59b7d74ed0f_add_component_category.py
Some firmwares only update one part of the system, e.g. the EC or ME firmware.
Other updates include all the updates needed for the whole system, and vendors
have been doing different things with the component name due to this.
Some examples of the brokenness:
* `Logitech Unifying Receiver` -> `Logitech Logitech Unifying Receiver`
* `Thunderbolt Firmware Update for AKiTiO Node Lite` -> `AKiTiO Thunderbolt Firmware Update for AKiTiO Node Lite`
* `Star LabTop Mk III Embedded Controller Firmware` -> `Star Labs Star LabTop Mk III Embedded Controller Firmware`
* `ChengMing 3967 System Update`
* `Thunderbolt Firmware Update for 0x07E6, XPS9370`
* `Z440/Z640/Z840 Workstation System BIOS`
The translator teams are also frustrated that they cannot translate terms like
`System Update` and also …
> Add a component property to express the firmware style

- app/templates/private.html
- app/templates/settings.html
- app/views.py
- app/views_settings.py
- plugins/auth-azure/__init__.py
- plugins/sign-gpg/__init__.py
- plugins/sign-pkcs7/__init__.py
- plugins/sign-sigul/__init__.py
- plugins/virustotal/__init__.py
- plugins/wu-copy/__init__.py
The number of plugins is too many to display as a nav. Promote the settings
view to a top level in the private menu.
This also allows us to use sensible names for the plugins.
> Do not use a nav header for settings

- app/__init__.py
- app/models.py
- app/templates/component-nav.html
- app/templates/component-overview.html
- app/templates/component-shards.html
- app/templates/device-shards-diff.html
- app/templates/device-shards.html
- app/templates/device.html
- app/templates/docs-news.html
- app/templates/private.html
- app/templates/shard-details.html
- app/templates/shard-list.html
- app/views_component.py
- app/views_device.py
- app/views_firmware.py
- app/views_shard.py
- cron.py
- lvfs_test.py
- migrations/versions/61b9b75cb259_add_component_shards.py
- plugins/chipsec/__init__.py
- plugins/dfu/__init__.py
- plugins/uefi-capsule/__init__.py
This allows us to show what modules make up each firmware volume, and in the
future means we can do attestation and verification of the installed modules.
At the moment it's really useful to see what modules are shared between models
and vendors, and would allow us to construct a blocklist in the future for
known broken firmware.
> Use CHIPSEC to add component shards for UEFI firmware

- app/metadata.py
This reduces the uncompressed metadata size from 1.1Mb to 916Kb which fixes
https://github.com/hughsie/lvfs-website/issues/335 for a little while.
> Only include the latest 5 releases for a component

- app/templates/private.html
- app/templates/settings-nav.html
- app/templates/settings-tests.html
- app/templates/settings.html
- app/views_settings.py
This is more useful when tracking down specific test failures, and with the
growth of the LVFS is more scalable than just showing everything for all tests.
> Show per-plugin test results in the admin view

- lvfs/pluginloader.py
- lvfs/templates/firmware-limits.html
* Fix minor typos of `theshold` → `threshold`
* No functional changes, but may affect translations
*As this is a very small change, I've skipped the usual breakdown and risk analysis*
> templates: Fix typos "theshold" -> "threshold"

- lvfs/templates/private.html
I got asked today how users are supposed to know what user level they are.
I think it's better to show in the header next to the 'person' rather than in
the profile view, the latter being where things get changed.
> Show the user capabilities in the headerbar

- lvfs/models.py
- lvfs/templates/dashboard.html
- lvfs/templates/firmware-details.html
- lvfs/templates/firmware-nav.html
- lvfs/templates/firmware-search.html
- lvfs/templates/private.html
- lvfs/templates/upload.html
- lvfs/templates/vendor-details.html
- lvfs/uploadedfile.py
- lvfs/views.py
- lvfs/views_firmware.py
- lvfs/views_report.py
- lvfs/views_vendor.py
- migrations/versions/38831f5bfa01_add_do_not_track.py
This allows either entire vendors to globally opt out of the download and
success reporting, or restrict it from specific firmware objects. Enabling the
LVFS::DoNotTrack feature disables a lot of the useful vendor functionality
(including the per-firmware limits and auto-demotion functionality) and is not
recommended by the LVFS admins.
> Allow firmware or vendors to enable DoNotTrack functionality

- lvfs/models.py
- lvfs/templates/metadata.html
- lvfs/templates/upload.html
- lvfs/templates/vendor-details.html
- lvfs/templates/vendorlist.html
- lvfs/views_vendor.py
Some OEMs have more than one vendor group on the LVFS. In this case the team
should be displayed in a different way to the OEM name, for instance we never
want to show 'Lenovo ThinkPad ThinkPad P50' when displaying firmware.
We can't migrate this automatically, as quite a few vendors are testing the
LVFS in secret and wouldn't want the internal team names exposed in the
migration scripts.
> Split up the vendor display name

- lvfs/models.py
- lvfs/templates/email-firmware-promote.txt
- lvfs/templates/email-firmware-uploaded.txt
- lvfs/templates/firmware-affiliation.html
- lvfs/templates/firmware-nav.html
- lvfs/templates/firmware-problems.html
- lvfs/templates/firmware-search.html
- lvfs/templates/profile.html
- lvfs/templates/vendor-affiliations.html
- lvfs/tests/lvfs_test.py
- lvfs/views_firmware.py
- lvfs/views_upload.py
- lvfs/views_user.py
- lvfs/views_vendor.py
- migrations/versions/44250e0a730e_add_affiliate_action.py
- migrations/versions/7cd25be1d3ee_add_notify_for_oem.py
To enforce this, we also need to add the concept of vendor namespaces.
The namespace prefix is the AppStream ID prefix that can be displayed to the
user. The OEM is the 'owner' of the ID prefix, and never the ODM. Add a
firmware 'problems' for existing firmware on the LVFS that hasn't already been
pushed to stable.
This prevents the ODM being 'credited' with the hardware when they are just
managing the entire end-to-end firmware lifecycle for the OEM as part of a
contract. Adding the actions to an ACL list allows us to better explain to the
vendor manager what the ODM is able to do, without hardcoding the logic.
Additionally, add an optional notfication email for ODM or OEM upload so that
the OEM is aware of what the ODM is doing.
Fixes https://github.com/fwupd/lvfs-website/issues/380
> Allow the OEM to control what the ODM is able to do

- cron.py
Only auto-demote based on reports uploaded in the last 6 months.
Fixes https://github.com/fwupd/lvfs-website/issues/383
> Don't auto-demote firmware because of old reports

- local.py
- lvfs/models.py
- lvfs/templates/firmware-problems.html
- lvfs/tests/lvfs_test.py
- plugins/chipsec/__init__.py
Some vendors were setting this to 'n/a' which was being included in the metadata.
> Check the source and release URLs are valid if provided

- cron.py
- lvfs/__init__.py
- lvfs/models.py
- lvfs/templates/email-modify.txt
- lvfs/templates/private.html
- lvfs/templates/query-list.html
- lvfs/templates/query-nav.html
- lvfs/templates/query-new.html
- lvfs/templates/query-show.html
- lvfs/templates/user-admin.html
- lvfs/templates/user-nav.html
- lvfs/templates/user-queries.html
- lvfs/templates/user-vendor.html
- lvfs/templates/vendor-users.html
- lvfs/tests/lvfs_test.py
- lvfs/views_query.py
- lvfs/views_user.py
- migrations/versions/4b78b3c65d57_add_yara_queries.py
Some security researchers want to run YARA queries on the firmware on the LVFS.
They can (and do) this already, but it means:
* Downloading tens of gigabytes of firmware using PULP_MANIFEST
* Exploding each cabinet to get the capsule
* Exploding each capsule into EFI binaries with chipsec
* Running yara on the command line
Given the LVFS already has the shards cached for each firmware, just allow
authenticated users to run YARA queries on the public firmware. These are done
in an existing cron job as they typically take a few minutes to compile and run.
It's important to note that this functionality isn't providing anything more
than people can do already with wget and a shell script and so I don't think
it's overstepping the mark allowing carefully chosen security researchers
access to …
> Allow researchers to run YARA queries on the public firmware

- lvfs/models.py
- lvfs/templates/component-overview.html
- lvfs/templates/device.html
- migrations/versions/d5d554c30ce4_component_claims.py
- plugins/blocklist/__init__.py
- plugins/blocklist/rules/backdoor-for-nsa.yar
- plugins/blocklist/rules/computrace.yar
- plugins/blocklist/rules/ibv-example-certificate.yar
- plugins/blocklist/rules/ibv-example-dmi-data.yar
This could be used for instance to detect Computrace, BootGuard or BIOSguard,
and used to provide helpful user information to the device model.
> Allow the blocklist plugin to add persistent claims

- lvfs/models.py
It doesn't make sense to pad them, as as soon as the component version get
over '99' the alignment changes anyway.
> trivial: Show the version format versions with no trailing zeros

- lvfs/components/routes.py
- lvfs/components/templates/component-overview.html
- lvfs/docs/templates/docs-metainfo-style.html
- lvfs/firmware/templates/firmware-components.html
- lvfs/models.py
- lvfs/upload/uploadedfile.py
- lvfs/upload/uploadedfile_test.py
- migrations/versions/ae8f6b33ba7d_component_release_id.py
This could be used, for instance, by Lenovo to specify a tag of `N1NET43W` for
a specific firmware release.
> Add a release tag to store the vendor-specific firmware identifier

- contrib/example.py
- lvfs/__init__.py
- lvfs/mdsync/routes.py
- lvfs/mdsync/routes_test.py
- lvfs/mdsync/templates/mdsync-list.html
- lvfs/mdsync/templates/mdsync-nav.html
- lvfs/mdsync/templates/mdsync-show.html
- lvfs/models.py
- lvfs/templates/private.html
- lvfs/users/routes.py
- lvfs/users/templates/user-admin.html
- migrations/versions/9b46ff543492_component_ref.py
External teams can contribute metadata about firmware releases from public
sources such as a vendor homepage or the general list downloaded from
Windows Update. This functionality allows us to check both that models have
been included on the LVFS and that matching versions are present.
Vendor managers are allowed to view this data, but only if the appstream ID
matches one of their assigned namespace prefixes.
> Allow syncing with other firmware databases

- lvfs/main/templates/dashboard.html
- lvfs/metadata/utils.py
- lvfs/models.py
- lvfs/search/templates/search.html
- lvfs/vendors/routes.py
- lvfs/vendors/templates/vendor-nav.html
- lvfs/vendors/templates/vendor-restrictions.html
- lvfs/vendors/templates/vendorlist-admin.html
At the moment I create vendor accounts for OEMs and ODMs for testing. I then
create them a first user account, and over time they add more accounts, upload
firmware, test with embargo on real hardware and then ask to be able to promote
to stable.
This default state means that the new user with the @trusted ACL can push
firmware for any vendors hardware as the vendor-id was never set. It's very easy
to forget to ask the vendor what ID to use as part of the onboarding process.
Move to a model where vendors are restricted by default, so that any missing
vendor-ids are caught during testing with embargo.
For OEMs like Dell and Lenovo make the 'unrestricted' vendor ID an explicit
step (with a vendor ID of '*') rather than just a side effect of never
assigning a vendor ID.
When deploying this …
> Include a vendor ID by default for testing accounts

- lvfs/main/routes.py
The DateTime object from postgresql is offset-aware, which humanize can't do.
> Always use offset-naive DateTime objects for humanize

- lvfs/components/templates/component-certificates.html
- lvfs/components/templates/component-shards.html
- lvfs/firmware/templates/firmware-tests.html
- lvfs/main/routes.py
- lvfs/pluginloader.py
- lvfs/settings/templates/settings.html
- lvfs/templates/private.html
- lvfs/tests/templates/test-list.html
- lvfs/tests/templates/test-overview.html
- plugins/amdpsp/__init__.py
- plugins/auth-azure/__init__.py
- plugins/blocklist/__init__.py
- plugins/cdn-purge/__init__.py
- plugins/chipsec/__init__.py
- plugins/clamav/__init__.py
- plugins/dfu/__init__.py
- plugins/info-readme/__init__.py
- plugins/intelme/__init__.py
- plugins/pecheck/__init__.py
- plugins/shard-claim/__init__.py
- plugins/sign-gpg/__init__.py
- plugins/sign-pkcs7/__init__.py
- plugins/sign-sigul/__init__.py
- plugins/uefi-capsule/__init__.py
- plugins/virustotal/__init__.py
- plugins/wu-copy/__init__.py
No plugins have to do anything non-static, and ninja doesn't mind if you try to
print a property that does not exist, but explodes if you try calling None.
> Use properties for the plugin name and summary

- lvfs/models.py
- lvfs/shards/routes.py
- lvfs/shards/routes_test.py
- lvfs/shards/templates/shard-checksums.html
- lvfs/shards/templates/shard-claims.html
- lvfs/shards/templates/shard-components.html
- lvfs/shards/templates/shard-details.html
- lvfs/shards/templates/shard-nav.html
- migrations/versions/58a8c79cd632_component_shard_claims.py
- plugins/shard-claim/__init__.py
This allows us to add negative security claims to components that contain shards
with known security problems, for instance older versions of UsbRt.
> Allow adding component claims based on the hash of a shard

- contrib/pylintrc
- lvfs/__init__.py
- lvfs/claims/routes.py
- lvfs/claims/routes_test.py
- lvfs/claims/templates/claim-details.html
- lvfs/claims/templates/claim-list.html
- lvfs/components/templates/component-overview.html
- lvfs/devices/templates/device-atom.xml
- lvfs/devices/templates/device.html
- lvfs/firmware/routes_test.py
- lvfs/models.py
- lvfs/shards/routes.py
- lvfs/shards/routes_test.py
- lvfs/shards/templates/shard-claims.html
- lvfs/shards/templates/shard-details.html
- lvfs/templates/private.html
- migrations/versions/2885e0d3f684_claim_as_object_migrate.py
- migrations/versions/9595113b929c_claim_as_object.py
- plugins/blocklist/__init__.py
- plugins/blocklist/rules/computrace.yar
- plugins/shard-claim/__init__.py
At the moment we just add a key=value attribute to each object that requires a
claim. This doesn't scale, and means we can never change claim icons from
something like 'info' to 'warning' without a database query that touches lots
of records in different tables. We also want to have a URL we can point the
user to for more information, for instance describing what BIOSGuard is,
and why it's a good thing.
To do this, create enumerated claim kinds that can be referenced by ID and
modified as required. We only really have a couple of existing claim types,
so we don't even need to worry too much about migrating data.
> Add Claim as a top level object

- lvfs/shards/routes.py
- lvfs/shards/routes_test.py
- lvfs/shards/templates/shard-list.html
If we want to add a Claim() on a component for a firmware that has not yet been
uploaded we need to be able to create the shard info manually.
This allows us to add 'danger'-class claims for GUIDs like SourceLevelDebugPkg
which should never exist on the LVFS.
> Allow creating a ComponentShardInfo manually

- lvfs/pluginloader.py
- plugins/blocklist/__init__.py
- plugins/pecheck/__init__.py
- plugins/shard-claim/__init__.py
This is only static, and so we can save some overhead making it a property.
> Switch the plugin order_after() to a property

- plugins/microcode-mcedb/__init__.py
This uses the database provided by MCExtractor and may produce false positives
as some microcode updates might be vendor or model specific.
> Add a plugin to identify old microcode versions

- plugins/microcode/__init__.py
Add a waivable test failure if the firmware contains a known-old version of
microcode. Use the built-in database of shard attributes for firmware already
on the LVFS, and fall back to the static database from MCExtractor.
Use the CPUID and platform to match the 'same' processor.
> Detect old versions of microcode

- lvfs/firmware/templates/firmware-details.html
> Do not show the raw iso3166 values in the firmware details

- cron.py
- lvfs/main/routes.py
- lvfs/main/routes_test.py
- lvfs/models.py
- migrations/versions/c26f0a8c9572_add_metrics.py
I'm going to be polling this several times a minute for a cool as-yet-unreleased
hardware project, so cache these to avoid database load.
> Add cached public stats of useful metrics

- lvfs/protocols/routes.py
Fix a crash where we try to set the verfmt to an unknown value.
> Allow a protocol to have no defined version format

- lvfs/metadata/utils.py
We are already checking this in fwupd when installing the downloaded file, but
for other tools that are just consuming the metadata it's very useful to have
it in the catalog too.
> Actually include LVFS::UpdateProtocol in the metadata

- lvfs/metadata/utils.py
The frontend should not have to do string searching to get the *known* category
type. We can't use ther plain 'categories' until we switch to using `.name` for
the `<name>` rather than `.name_with_category` -- which we can't realistically
do until more of the clients downloading firmware have been updated to newer
versons.
Basically, err on odd rather than breaking things.
> Add category information to the metadata

- cron.py
- lvfs/components/routes.py
- lvfs/components/templates/component-checksums.html
- lvfs/components/templates/component-issues.html
- lvfs/components/templates/component-keywords.html
- lvfs/components/templates/component-overview.html
- lvfs/components/templates/component-requires-advanced.html
- lvfs/components/templates/component-requires.html
- lvfs/components/templates/component-update.html
- lvfs/mdsync/routes.py
- lvfs/metadata/utils.py
- lvfs/models.py
- lvfs/upload/uploadedfile.py
One of the common tripping points for OEMs and ODMs is that the uploaded
firmware.metainfo.xml does not get rewritten if requirements are added or other
changes are made on the LVFS UI.
Although we use the metadata to know what firmware file to download, we use
the 'as uploaded' metadata when actually installing the firmware. By rewriting
the metainfo we can ensure the two information sources match.
This does of course change the downloaded file checksum, but this is not being
served by the CDN.
> Rewrite the metainfo when signing the firmware

- cron.py
- lvfs/templates/email-firmware-obsolete.txt
There are hundreds of forgotten firmware files sitting in embargo where newer
versions exist in either testing or stable. Delete them, sending email, so that
users either undelete and move to stable, or allow them to be auto-purged after
an additional three months.
> Delete firmware in embargo with newer public versions

- lvfs/metadata/utils.py
- lvfs/models.py
- lvfs/pluginloader.py
- plugins/cdn-mirror/__init__.py
- requirements.txt
When the screenshot image is loaded on the client system we download the file
from the vendor specified URL. This would cause the client to ping an external
vendor on firmware install, leaking the user agent and IP address.
This probably is not what the user is expecting and certainly not mentioned in
our privacy policy.
Download the image locally when running tests, and use a CDN URL in the public
metadata, fixing the privacy issue.
> Rewrite the AppStream screenshot URL to use the server CDN

- cron.py
- lvfs/metadata/routes.py
- lvfs/metadata/templates/metadata.html
- lvfs/models.py
When a fwupd client wants to refresh the metadata it firsts download the tiny
signature (typically a JCat file) and then if that has changed compared to the
existing signature on disk the much larged gzipped XML metadata catalog is then
downloaded. This saves a lot of mirror bandwidth as some remotes do not change
very much, and even stable only regenerates 4 times a day.
The drawback of this is that we have two things that need to be used to verify
a signature, and one of four scenarios could happen:
1. The same version of sig and catalog are delivered by the CDN
2. Between getting the sig the remote is resigned and the CDN is invalidated
3. The CDN sends an older cached version of the sig and the current catalog
4. The CDN sends the current sig and a cached older version of the catalog …
> Write metadata with a build suffix to prevent CDN mismatch

- lvfs/components/routes.py
- lvfs/components/templates/component-update.html
- lvfs/metadata/utils.py
- lvfs/models.py
- lvfs/upload/uploadedfile.py
- migrations/versions/6e1c3e4cfe3c_release_message.py
Vendors are uploading firmware with this metadata tag set, and it's being
stripped out when we re-write the metainfo.xml during signing.
> Add support for LVFS::UpdateMessage

- lvfs/firmware/routes.py
- lvfs/firmware/routes_test.py
At the moment QA users are restricted to seeing any firmware either uploaded by
them, or owned by their vendor. This work fine for OEMs.
For ODMs who are uploading on behalf of other OEMs we need to relax the rules a
little, and allow QA users to see any firmware uploaded by any users in their
own vendor group, regardless of what OEM actually owns the firmware now.
For most non-ODM vendors this change will have no effective change.
> Allow QA users to see all ODM firmware uploaded

- lvfs/firmware/routes.py
- lvfs/models.py
- lvfs/upload/routes.py
- migrations/versions/79fd156f0f48_firmware_vendor_odm_id_nonnull.py
- migrations/versions/bf6316b24565_firmware_vendor_odm_id.py
Doing a subsquery of all users in a vendor group takes a lot of time in large
vendors like Dell and Lenovo.
One extra indexed integer will speed things up a lot!
> Store the upload vendor in the database directly

- lvfs/metadata/utils.py
At the moment we're saving duplicates when an ODM has released multiple versions
of firmware for the same hardware.
@@ -18038,8 +18023,6 @@
</releases>
<requires>
<firmware compare="eq" version="USB:0x273F">vendor-id</firmware>
-      <firmware compare="eq" version="USB:0x273F">vendor-id</firmware>
-      <firmware compare="eq" version="USB:0x273F">vendor-id</firmware>
</requires>
</component>
<component type="firmware">
> Do not save duplicate <requires>vendor-id</> tags to the metadata

- lvfs/__init__.py
- lvfs/hsireports/routes.py
- lvfs/hsireports/routes_test.py
- lvfs/hsireports/templates/hsireport-details.html
- lvfs/hsireports/templates/hsireport-list.html
- lvfs/hsireports/templates/hsireport-nav.html
- lvfs/models.py
- lvfs/templates/private.html
- migrations/versions/3dc586299daf_hsi_reports.py
At the moment we just show the last 100 HSI reports, but with more data it can
be correlated back to the Firmware() and/or Vendor() objects so we can show a
per-model overview of the submitted HSI values.
This is intended to influence customer purchasing decisions.
> Allow clients to upload anonymous HSI attrs

- lvfs/analytics/templates/analytics-reports.html
- lvfs/firmware/templates/firmware-analytics-reports.html
- lvfs/issues/routes.py
- lvfs/issues/templates/issue-reports.html
- lvfs/models.py
- lvfs/reports/routes.py
- lvfs/reports/routes_test.py
Use stacked subqueries to do all the heavy lifting on the database server. It
turns out databases are good at doing database things.
This speeds up showing matching reports from over 60 seconds in the worst case,
(often timing out the uwsgi socket) to ~150ms which is more than acceptable.
> Improve the report query speed by several orders of magnitude

- lvfs/static/theme.css
Changes color of search input from dark gray to white. This increases the contrast which makes the search input easier to read.
> Changes color of search input

- lvfs/mdsync/routes.py
- lvfs/models.py
The actual number of reports (which will be related to the number of firmware
downloads) is a private stat we can't share with anyone; however it would be
really useful to know the order of magnitude of reports. This way 50% failure
with just two reports would not trigger any alarms.
The high/medium/low states are granular enough to be useful, but should not
leak numbers that OEMs might consider private.
> Export the success confidence to the mdsync vendor

- lvfs/components/routes.py
- lvfs/firmware/routes.py
- lvfs/tests/routes.py
- lvfs/tests/utils.py
- lvfs/upload/routes.py
Something isn't scheduling tests correctly, and until we work out what it is
run all pending tests on a timer.
> Run any pending tests every 60 minutes

- lvfs/main/routes.py
If we called /lvfs/login manually using curl, with a username that matched a
Vendor.oauth_domain_glob then we would create a user and the session would be
marked as logged in. Thankfully the schema check on the database for a missing
username saves us, resulting in a uwsgi stacktrace and a 'LVFS is unavailable'
error instead.
The missing code just informs the user that they have to use the *other*
button in the login screen, which I presume was the reason for the call to
`_create_user_for_oauth_username()` in the first place...
Spotted by Justin Steven <justin@justinsteven.com>, many thanks.
> Do not allow users requiring OAuth to use /lvfs/login

- cron.py
- lvfs/vendors/routes.py
- lvfs/vendors/utils.py
Users could 'guess' vendors who are on the LVFS but not visible by incrementing
the integer vendor key and seeing the new logo.
Use a HMAC of the group ID and rename the existing logo files.
Spotted by Justin Steven <justin@justinsteven.com>, many thanks.
> Use a non-predictable vendor icon filename

- lvfs/analytics/templates/analytics-clients.html
- lvfs/dbutils.py
- lvfs/main/routes.py
- lvfs/models.py
- migrations/versions/9bc9ca984cda_remove_client_addr.py
We already use the recent nginx for abuse detection, and we don't seem to use
the hashed client address anywhere useful in the LVFS.
The SHA1 hash is not terribly secure (even salted) and removing PII we do not
actually use seems a sane thing to do.
Spotted by Justin Steven <justin@justinsteven.com>, many thanks.
> Do not store the client address in the database

- lvfs/__init__.py
Flask-SQLAlchemy already does this, so I think it's a NOP to do it twice.
> Do not remove the scoped session

- cron.py
- lvfs/upload/uploadedfile.py
- lvfs/util.py
Pulp cannot deal with filenames with comma chars in the filename as it is used
for the PULP_MANIFEST delimiter. Changing pulp-server to use `.rsplit()` rather
then `.split()` on all supported deployments is somewhat unlikely at this point.
Also, ensure the filename is restricted to ASCII encoding, as mirror targets
might be on filesystems that do not handle all of UTF-8 correctly.
This affects exactly one firmware on the LVFS.
> Ensure that all archive filenames are valid for PULP

- lvfs/devices/templates/devicelist.html
Related to https://github.com/fwupd/lvfs-website/pull/689 .
I have updated an old link that is not correct anymore because the structure of the website has changed. As per the discussion in https://github.com/fwupd/lvfs-website/pull/689 I have now used a dynamic link instead of a hardcoded link.
> Replace old, static link in devicelist.html with dynamic link (fixed)

- lvfs/firmware/utils.py
The current 6 month value means vendors often have huge amounts of deleted
firmware, and we're using huge amounts of disk space now.
> Purge firmware that is deleted after just 30 days

- lvfs/models.py
- lvfs/vendors/templates/vendorlist.html
Related to https://github.com/fwupd/lvfs-website/issues/721
The wording "uploaded recently" should be changed to "uploaded in the last 6 months" to make it more comprehensible.
> Vendorlist: change "recently" to "last 6 months"

- lvfs/devices/templates/devicelist.html
While the section "Devices supported by the LVFS" on https://fwupd.org/lvfs/devices/ has a card-text, the section "Latest Devices Supported" does not. To increase consistency I would like to add a card-text for this section as well.
> Add card-text for latest devices supported

- lvfs/metadata/routes.py
This allows us to run local.py without redis running.
> Do not configure celery during init

- lvfs/metadata/utils.py
Given only about 30% of downloads come from fwupd >= 1.3.6 I think we need to
be a bit more pragmatic about this for the time being.
> Do not apply vendor-id restrictions for UEFI devices

- cron.py
- docs/source/apply.rst
- lvfs/dbutils.py
- lvfs/mdsync/routes_test.py
- lvfs/models.py
- lvfs/vendors/routes.py
- lvfs/vendors/templates/vendor-details.html
- migrations/versions/fbf18115ec00_vendor_legal_name.py
In some cases the vendor legal name will be very different from the thing from
what the user expects to see, for instance 'ASUSTeK Computer Inc.' -> 'ASUS'.
We can use this extra field to show the legal string for legal agreements and
the display name everywhere else.
> Add a vendor legal name

- lvfs/components/routes_test.py
- lvfs/models.py
If the uploader makes this mistake then we would display 'ASUS ASUS System'
on the LVFS and the various end-user tools.
> Do not allow the vendor name in the firmware name

- lvfs/components/routes.py
- lvfs/components/routes_test.py
- lvfs/util.py
Autoimporting issues is hugely useful for uploaders, but several have not been
checking the 'fixed up' update descriptions for sanity, leading to bugs like
https://github.com/fwupd/lvfs-website/issues/758 that keep popping up.
There's no way we can possibly try to make the description sane in all cases,
so just force the uploader to remove the REMOVE_ME keywords and they'll
hopefully make the description a bit easier to read at the same time.
> Force the uploader after autoimporting issues
