fwupd/lvfs-website

README.md
contrib/keys.pp.in
contrib/lvfs.pp

There still is a database, so we can't exactly shoot the instance in the head
but it means we can spin up a test instance much easier.
Still WIP, there's lots of stuff still to do properly.

Use Puppet to set up the server

---

app/pluginloader.py
app/views.py
plugins/info-readme/__init__.py
plugins/info-readme/template.txt

Ths idea is we explain that we're re-packed the archive from the vendor and
that the LVFS authors are not liable if you brick your computer.

Add a plugin to add a README file to the archive

---

app/db.py
app/models.py
app/templates/default.html
app/templates/telemetry.html
app/views_firmware.py
schema.sql

Use this to update the database:
ALTER TABLE firmware ADD download_cnt INT DEFAULT 0;
CREATE INDEX filename_idx ON clients (filename(40));
Fixes https://github.com/hughsie/lvfs-website/issues/32

Add some vendor telemetry data for each firmware file

---

app/pluginloader.py
plugins/sign-gpg/__init__.py
plugins/sign-pkcs7/__init__.py
uploadedfile_test.py

Fixes: https://github.com/hughsie/lvfs-website/issues/49

Do not try to re-sign firmware referenced from multiple metainfo files

---

app/templates/default.html

Advice welcome for the text above the username/password entries. I wanted to make it  clear that normal users don't have to log in.

Move the login entries into a modal dialog

---

app/db.py
app/models.py
app/templates/firmware-details.html
app/views_firmware.py
app/views_upload.py
lvfs_test.py

I'm not super happy with the "Promotions" name -- any better ideas welcome. It's really a table that hold what user moved the firmware to different targets, and when they did it.

Create a table to log when firmware moves between different targets

---

app/models.py
app/templates/firmware-details.html
app/views.py
contrib/Dockerfile

Show a warning when trying to promote a firmware into stable that has spent
less than a day in testing.

trivial: Try to convince people to use the testing target

---

app/templates/firmware-details.html
app/views_firmware.py

Fixes https://github.com/hughsie/lvfs-website/issues/77

Require urgency and release notes before moving to stable

---

plugins/sign-sigul/__init__.py

Fixes https://github.com/hughsie/lvfs-website/issues/87

Add support for signing firmware using Sigul

---

app/models.py
app/templates/firmware-details.html
app/templates/upload.html
app/templates/vendor-details.html
app/views_vendor.py
migrations/versions/44e3334bb64e_embargo_upload_default.py

Fixes: https://github.com/hughsie/lvfs-website/issues/100

Allow uploading by default to embargo for some vendors

---

app/views_upload.py

Fixes https://github.com/hughsie/lvfs-website/issues/122
I've pushed this to staging, can you test please?

Allow uploading duplicate components in composite firmwares

---

app/templates/email-modify.txt
app/views_vendor.py

Fixes: https://github.com/hughsie/lvfs-website/issues/142

If OAuth is configured don't create local users

---

app/emails.py
app/models.py
app/templates/default.html
app/templates/email-recover-password.txt
app/templates/email-recover.txt
app/templates/user-recover.html
app/views_user.py
lvfs_test.py
migrations/versions/cf1db1cb7fce_add_password_recovery.py

Fixes https://github.com/hughsie/lvfs-website/issues/141

Allow the user to recover from a lost password

---

app/views_firmware.py
app/views_upload.py

Fixes: https://github.com/hughsie/lvfs-website/issues/143
110% untested.

Autodelete duplicate firmware uploaded by robots

---

plugins/cdn-purge/__init__.py

This will be the CDN provider after the move to the Linux Foundation.

Make the CDN plugin more generic to support CDNs such as Fastly

---

app/models.py
app/templates/docs-metainfo.html
app/templates/firmware-md-update.html
app/views_component.py
app/views_upload.py
contrib/Dockerfile
migrations/versions/687f5c4d0aa3_add_component_install_duration.py

This will need a new appstream-glib release to pass CI. I'm waiting to hear back from the AppStream maintainer about the release property name to use.

Add the install duration to the Component

---

app/dbutils.py
app/models.py
app/templates/user-admin.html
app/templates/userlist.html
app/views.py
app/views_user.py
migrations/versions/0e38974d7935_remove_legacy_usernames.py

We've been warning about this for quite some time, and actually logging in with
a legacy username has been disallowed for over 6 months now.

Remove the legacy usernames

---

app/templates/device.html
app/views.py

Show the device descriptions in HTML, rather than the internal markdown form.

Improve the appearance of the device update page

---

app/models.py
app/views.py
app/views_user.py
migrations/versions/8f394b9db1f0_add_password_timestamp.py

This will be used on initial login from account creation, and also if they've
used the password reset feature.
Fixes https://github.com/hughsie/lvfs-website/issues/117

Prompt the user to change thier password when required

---

app/templates/firmware-details.html
cron.py

Automatically purge firmware that has been in the deleted state for 6 months or
more.
Fixes https://github.com/hughsie/lvfs-website/issues/215

Delete very old deleted firmware

---

app/views_upload.py

Fixes: https://github.com/hughsie/lvfs-website/issues/225

Split hardware requires in the metainfo file

---

app/hash.py
app/models.py
app/static/style.css
app/templates/default.html
app/templates/email-confirm.txt
app/templates/login1.html
app/templates/login2.html
app/templates/profile.html
app/templates/user-admin.html
app/templates/vendor-users.html
app/views.py
app/views_user.py
migrations/versions/1df57688bcc5_add_otp_secret.py
requirements.txt

Fixes https://github.com/hughsie/lvfs-website/issues/239

Add 2 factor authentication using OTP

---

app/templates/email-confirm.txt

At the moment it's super hard to discover this resource that a lot of people
really should be reading.

Advertise the mailing list when a new user gets added

---

app/models.py
app/static/img/symbolic-download.svg
app/static/img/symbolic-embargo.svg
app/static/img/symbolic-private.svg
app/static/img/symbolic-problem.svg
app/static/img/symbolic-stable.svg
app/static/img/symbolic-testing.svg
app/static/img/symbolic-trash.svg
app/templates/firmware.html
app/views.py
lvfs_test.py

I spend a lot of time looking at this, so make it look nice.

Make the firmware page more beautiful

---

plugins/dfu/__init__.py

These are similar to the checks done for UEFI capsules.

Test the DFU footer for firmwares with protocol org.usb.dfu

---

app/models.py
app/templates/docs-metainfo-protocol.html
app/templates/protocol-details.html
app/templates/protocol-list.html
app/views_protocol.py
migrations/versions/4641acfd71e3_add_protocol_has_header.py

FIXME: needs Alembic migration script

Add metadata about whether a firmware has a testable header

---

app/models.py
app/templates/index.html
app/templates/vendor-details.html
app/views_vendor.py
migrations/versions/5eaa6ae92bb7_add_vendor_quotes.py

This makes the front page more engaging. With the theme change we can make
these look better, but cards will do until we have more quotes.

Add quotes to the front page

---

app/models.py
app/views.py
cron.py
migrations/versions/65b618b6e525_add_analyticvendor.py

This takes the page load time for the most active users from 2.5s to 200ms.

Generate the vendor download data in a cron job

---

app/models.py

Add an extra 'tick' for firmware that supplies a source URL

---

app/templates/docs-metainfo-intro.html
app/uploadedfile.py
app/util.py
app/views_component.py
uploadedfile_test.py

Fixes https://github.com/hughsie/fwupd/issues/1103

Ensure the firmware-flashed value is a valid lowercase GUID

---

plugins/virustotal/__init__.py

This is easier to extract for VirusTotal, and actually less work for us too now
we have the contents blob caching.

virustotal: Upload the firmware contents rather than the cabinet archive

---

app/models.py
app/templates/firmware-tests.html
app/templates/test-list.html
app/views_test.py
migrations/versions/1e56e78afabc_add_test_scheduled_ts.py

To fix this properly we needed to create a 'scheduled_ts' that was always
set to something non-zero.

Order the tests by time

---

app/models.py
app/templates/category-details.html
app/views_category.py
migrations/versions/27397ef70315_add_category_expect_device_checksum.py

Updating these kinds of device will not change the device checksum.

Do not expect device checksums for ME or EC firmware

---

app/models.py
app/templates/vendor-details.html
app/templates/vendor-exports.html
app/templates/vendor-nav.html
app/views.py
app/views_vendor.py
requirements.txt

Allow managers to edit their own list of embargoed countries

---

.gitignore
report.py

The CSV output can be used for CVE generation, for example...

Add a simple script to report test failures

---

plugins/blocklist/__init__.py

This allows us to help the OEMs with identifying the problem.

Allow extra description text for the blocklist plugin

---

cron.py
lvfs/models.py
lvfs/pluginloader.py
lvfs/templates/docs-news.html
lvfs/templates/email-firmware-demote.txt
lvfs/templates/firmware-limits.html
lvfs/templates/profile.html
lvfs/tests/lvfs_test.py
lvfs/tests/uploadedfile_test.py
lvfs/uploadedfile.py
lvfs/views_firmware.py
lvfs/views_upload.py
lvfs/views_user.py
migrations/versions/d1b89f7256f6_add_failure_percentage.py

Automatically demote firmware with >5 failures and a success rate of <70%

---

lvfs/templates/dashboard.html
lvfs/templates/private.html
lvfs/templates/upload.html
lvfs/tests/lvfs_test.py
lvfs/views_agreement.py
lvfs/views_upload.py

This fixes a regression when uploading firmware automatically.

Allow uploads from robot users without CSRF protections

---

lvfs/views.py

Fixes half of https://github.com/fwupd/lvfs-website/issues/384

Do not show deleted firmware on the recent list on the dashboard

---

lvfs/views_upload.py

Use a sane error message on upload when a component drops a GUID

---

lvfs/models.py
lvfs/templates/search.html
lvfs/templates/vendor-details.html
lvfs/templates/vendorlist.html
lvfs/tests/lvfs_test.py
lvfs/views_vendor.py
migrations/versions/1822ddbf2a73_remove_vendor_bools.py

This allows the page to be usable on mobile and provides more content without
disclosing vendor secrets.
Fixes: https://github.com/fwupd/lvfs-website/issues/391

Redesign the user list to use bootstrap cards

---

lvfs/templates/component-update.html

This is probably the simplest way to define a mapping...
Fixes https://github.com/fwupd/lvfs-website/issues/320

Add more common update severity terms in the update detail page

---

cron.py
lvfs/models.py

Also, increase the timeout for stable remotes to reduce CDN churn.
Fixes https://github.com/fwupd/lvfs-website/issues/397

Regenerate embargo remotes ever 5 minutes

---

lvfs/templates/docs-archive.html
lvfs/templates/private.html
lvfs/templates/public.html
lvfs/views.py

Fixes https://github.com/fwupd/fwupd/issues/1429

Add some documentation on how to create the archive

---

lvfs/tests/lvfs_test.py
plugins/blocklist/__init__.py
plugins/blocklist/rules/backdoor-for-nsa.yar
plugins/blocklist/rules/ibv-example-certificate.yar
plugins/blocklist/rules/ibv-example-dmi-data.yar
requirements.txt

This will allow us to write more complicated rules in the future that are not
just searching for simple strings.

Use YARA in preference to our dumb blocklist plugin

---

plugins/amdpsp/__init__.py
plugins/amdpsp/debug.py
requirements.txt

This is very similar to how the IntelME parser works.

Use PSPTool to parse the AMD PSP section

---

lvfs/main/routes.py

Else uploading from a cron job can fail.

trivial: Don't require CSRF for login

---

cron.py
lvfs/__init__.py
lvfs/dbutils.py
lvfs/firmware/routes.py
lvfs/firmware/routes_test.py
lvfs/main/templates/profile.html
lvfs/metadata/templates/metadata.html
lvfs/models.py
lvfs/reports/routes.py
lvfs/templates/email-modify.txt
lvfs/templates/private.html
lvfs/testcase.py
lvfs/upload/routes.py
lvfs/users/routes.py
lvfs/users/templates/user-admin.html
lvfs/users/templates/user-vendor.html
lvfs/vendors/routes.py
lvfs/vendors/templates/vendor-users.html
migrations/versions/ef0591734691_user_action.py

It was crazy that we had to modify the database schema every time we added a
new ACL or notification type.

Move the user actions from the main table

---

lvfs/docs/templates/docs-metainfo-version.html

Fixes https://github.com/fwupd/lvfs-website/issues/433

Clarify that more vendors should use LVFS::VersionFormat

---

lvfs/components/routes.py
lvfs/components/templates/component-requires-advanced.html
lvfs/docs/templates/docs-metainfo-restrict.html
lvfs/metadata/utils.py
lvfs/models.py
lvfs/upload/uploadedfile.py
migrations/versions/2411ea0a8bf9_requirement-add-depth.py

Add support for matching <firmware> requirements on device parents

---

lvfs/docs/routes.py
lvfs/docs/templates/docs-consulting.html
lvfs/main/templates/index.html
lvfs/models.py
lvfs/templates/private.html
lvfs/templates/public.html
lvfs/vendors/routes.py
lvfs/vendors/templates/vendor-details.html
migrations/versions/946c9e47ceaa_consulting.py

Fixes https://github.com/fwupd/lvfs-website/issues/440
WIP until we have at least 2 companies willing to be included here :)

Add a page to list consultants that can work on the LVFS

---

lvfs/models.py

It's just going to result in an explosion.

Never try to verify the password of a disabled users

---

cron.py

Loading all the thousands of Component objects ahead-of-time means that
sqlalchemy.orm.state.InstanceState starts showing up on profiles using
gigabytes of memory. This makes the small production machine unhappy.
To make it more GC-friendly, load the list of components as integers and then
fetch then ORM objects as required during each query.
This reduces the amount of memory to do a simple yara query on all firmware
from +3Gb to ~300kb.

Reduce the memory consumption when running yara queries

---

cron.py
lvfs/analytics/routes_test.py
lvfs/dbutils.py
lvfs/firmware/routes_test.py
lvfs/metadata/utils.py
lvfs/models.py
lvfs/reports/routes.py
lvfs/testcase.py
lvfs/upload/routes.py
lvfs/upload/routes_test.py
lvfs/upload/uploadedfile.py
lvfs/vendors/routes.py
lvfs/vendors/routes_test.py
migrations/versions/43f3d6d89335_checksum_upload_sha256.py

Fixes https://github.com/fwupd/lvfs-website/issues/410

Use SHA256 when storing the upload checksum

---

contrib/led/90-lvfs-led.rules
contrib/led/Makefile
contrib/led/README.md
contrib/led/lvfs-led.py
contrib/led/lvfs-led@.service
requirements.txt

This is really a toy, and is only used to make myself feel warm and fuzzy.
@superm1 if you want me to send you some hardware, let me know -- I made one spare just in case. :)

Add a script to show the download count on an external LED panel

---

cron.py
jcat/__init__.py
jcat/jcatblob.py
jcat/tests/jcat_test.py

Also, if SHA256 is ever broken it's very unlikely to have an attack where the
SHA1 hash is also valid...

Add support for SHA-1 too

---

lvfs/models.py

I recall this was moved into the UX and database, so hopefully this was the only place needed.
LVFS side of https://github.com/fwupd/fwupd/pull/1842

add hex verfmt to models

---

lvfs/firmware/routes.py
lvfs/templates/private.html

If the user is a QA or analyst user then there is no way to get the short list
of uploaded firmware.

Add a filter view for user uploaded firmware

---

lvfs/main/routes.py

Fixes https://github.com/fwupd/lvfs-website/issues/608

Redirect https://fwupd.org/downloads/ back to https://fwupd.org/

---

lvfs/firmware/templates/firmware-details.html

A new OEM was getting very confused.

Make it more obvious that the firmware is waiting to be signed

---

lvfs/users/routes.py
lvfs/users/templates/userlist-nav.html
lvfs/users/templates/userlist.html

This lets the admin filter by user ACL.

Add filtering options for users

---

lvfs/docs/templates/docs-users.html

Fix a typo

---

lvfs/__init__.py

This has never worked properly and complicates a critical part of the web-app.

Remove the app.logger.addHandler alert

---

contrib/sync-pulp.py

This is much more lightweight than installing pulp-server from a random website
just for one simple client utility.

Add a helper script to populate a directory from a PULP_MANIFEST

---

lvfs/firmware/templates/firmware-new.html

- show --> shows
- include number of listed firmwares (50)
- newest --> latest

fix spelling and wording on template firmware-new.html

---

lvfs/firmware/templates/firmware-new.html

Fixes https://github.com/fwupd/lvfs-website/issues/740

Make the 'New firmware' page more mobile-friendly

---

lvfs/analytics/routes.py
lvfs/templates/private.html

The LF asked when was the busiest part of the day; I had no idea. Now I do.

Add a per-day download graph

---

lvfs/metadata/utils.py

This has the effect of 'breaking' firmware updates for vendors who have not
supplied the vendor_id strings ONLY for firmware in embargo. It does not break
components already being consumed by users.
Email asking about `XXX:NEVER_GOING_TO_MATCH` incoming in 5...4...3...2...1 :)

Allow unrestricted vendor accounts only for public remotes

---

docs/source/metainfo.rst
lvfs/components/routes.py
lvfs/models.py
lvfs/util.py

It would be useful to index and search for these.

Support the Intel technical advisory issue tags

---

contrib/example.py

Fixes https://github.com/fwupd/lvfs-website/issues/795

Retry the network action if it fails
